### ISSUE TITLE
Add animations to icons

### ISSUE THREAD

**Issue by avenmia** [avenmia/PersonalWebsite#66]
```css
.link a {
    color: #ffedd6;
    background-color: #000;
    transition: all 10s ease-out;
    border-radius: 50%;
    width: 52px;
    height: 52px;
    display: inline-block;
    box-sizing: border-box;
}
```
